version: '3'
services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
#    command: ng serve --host 0.0.0.0 --poll=1000