FROM node:16-alpine

# development server (ng serve) as an unprivileged user
RUN mkdir /app && chown node:node /app
WORKDIR /app
USER node

COPY --chown=node:node package*.json ./
RUN npm ci

COPY --chown=node:node . .

EXPOSE 4200

CMD ["npm", "run", "serve"]
